name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ORG_NAME: "returngis"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Authentication GH Packages
      run: dotnet nuget add source --username 0GiS0 --password ${{ secrets.PAT_PACKAGES }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.ORG_NAME }}/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
