name: 🚦 Environments demo
on:
  workflow_dispatch:


jobs:

  deploy-dev:
    environment: 
        name: dev
        url: https://dev.example.com

    runs-on: ubuntu-latest
    steps:
      - run: |          
          echo "🎉 This is a variable for dev environment only: ${{ vars.SOME_VARIABLE }}"          
  deploy-staging:
    needs: deploy-dev
    environment: 
        name: staging
        url: https://staging.example.com
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "🎉 This is a variable for staging environment only: ${{ vars.SOME_VARIABLE }}"
  deploy-prod:
    needs: deploy-staging
    environment: 
        name: prod
        url: https://example.com
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "🎉 This is a variable for production environment only: ${{ vars.SOME_VARIABLE }}"