name: GitHub-hosted runners
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  ubuntu-job:    
    runs-on: ubuntu-latest
    steps:
    - run: |
        os_version=$(cat /etc/os-release)
        echo "🎉 This job uses:"
        echo $os_version
  windows-job:    
    runs-on: windows-latest
    steps:
    - run: |
        $os_version = [System.Environment]::OSVersion.Version
        echo "🎉 This job uses:"
        echo $os_version
  macos-job:    
    runs-on: macos-latest
    steps:
    - run: |
        sw_version=$(sw_vers)
        echo "🎉 This job uses:"
        echo $sw_version
