name: job-from-jenkins
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: echo message
      run: echo Building..
    - name: sh
      shell: bash
      run: dotnet build
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: echo message
      run: echo Testing..
    - name: sh
      shell: bash
      run: dotnet test
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: echo message
      run: echo Deploying..
    - name: sh
      shell: bash
      run: dotnet publish -c Release -o ./publish
