name: Self-hosted runner demo

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
    self-hosted-runner-job:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - run: |
                sw_version=$(sw_vers)
                echo "🎉 This job uses:"
                echo $sw_version