name: Secrets

on:
  workflow_dispatch:

env:
  CHECK_SECRET: ${{ secrets.SECRET_FOR_IF}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: My first secret
        run: echo ${{ secrets.MY_SECRET}}
      - name: Check secret
        if: env.CHECK_SECRET == 'true'
        run: echo $CHECK_SECRET
      - name: Secret at org level
        run: echo ${{ secrets.SECRET_FOR_ORG}}
      - name: Secret at repo level
        run: echo ${{ secrets.SECRET_FOR_REPO}}
      - name: If a secret with the same name exists at multiple levels, the secret at the lowest level takes precedence
        run: echo ${{ secrets.REUSED_SECRET_NAME}}
      - name: Decrypt a secret using a secret
        run: |
         gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" \
            --output $HOME/secrets/my_secret.json larger_secret.txt.gpg
